version: '3'

volumes:
  docker_config_gen:
    external: true
    name: ${DOCKER_CONFIG_GEN_VOLUME:-docker_config_gen}

services:
  docker-config-gen:
    image: antimatter-studios/docker-config-gen:latest
    container_name: docker-config-gen
    command: npx nodemon docker-config-gen.mjs
    build:
      context: .
      args:
        - RUN_YARN=${RUN_YARN:-false}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - docker_config_gen:/config
      - $PWD:/app
    environment:
      CONFIG_PATH: /config
      DEBUG: true
