version: '3'

volumes:
  ddt_config_gen:
    external: true
    name: ddt_config_gen

services:
  docker-config-gen:
    image: antimatter-studios/docker-config-gen:latest
    container_name: docker-config-gen
    command: npx nodemon config-gen.mjs
    build:
      context: .
      args:
        - RUN_YARN=false
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ddt_config_gen:/config
      - $PWD:/app
    environment:
      CONFIG_PATH: /config


