version: '3'

services:
  docker-config-gen:
    image: ghcr.io/antimatter-studios/docker-config-gen:latest
    container_name: docker-config-gen
    build:
      context: .
      args:
        - RUN_YARN=${RUN_YARN:-false}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD:/app
    environment:
      DEBUG: ${DEBUG:-false}
